[package]
name = "rustdoc-markdown"
version = "0.1.0"
edition = "2021"

[dependencies]
public-api = "0.37.0"
rustdoc-json = "0.9.2"
rustdoc-types = "0.28.1"
serde_json = "1.0.122"
markdown-writer = { path = "../markdown-writer" }
