[package]
name = "rustdoc-markdown"
version = "0.1.0"
edition = "2021"

[dependencies]
rustdoc-code-formatter = { path = "../rustdoc-code-formatter" }
markdown-writer = { path = "../markdown-writer" }
